---
title:  "Software Carpentry"
subtitle: "@ Uni Trento"
shorttitle: "SWC Trento"
author:
- name: Marianne Corvellec
  short: Corvellec
- name: Lachlan Deer
  short: Deer
  speaker: true
useshortauthors: true
toc: false
date: Novemeber 2018
section-titles: true
...
