---
title:  "A Strategy to Defeat Whitewalkers:"
subtitle: "Will Dragons Suffice?"
shorttitle: "Defeating Whitewalkers with Dragons"
author:
- name: Jon Snow
  short: Snow
  institute: 1
  speaker: true
- name: Daenerys Targaryen
  short: Targaryen
  institute: 2
institute:
- name: House Stark
  short: Stark
  id: 1
- name: House Targaryen
  short: Targaryen
  id: 2
useshortauthors: true
toc: false
date: Fall 2019
section-titles: true
...
